branches:
  - name: "main"
  - name: "beta"
    prerelease: "snapshot"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - [ '@semantic-release/exec', {
    prepareCmd: 'sed -i.bak "s/atala-prism-sdk:${lastRelease.version}/atala-prism-sdk:${nextRelease.version}/g" ./tests/end-to-end/build.gradle.kts && rm -f ./tests/end-to-end/build.gradle.kts.bak' } ]
  - ["@semantic-release/changelog", {changelogFile: "CHANGELOG.md"}]
  - "gradle-semantic-release-plugin"
  - [
    "@semantic-release/git",
    {
      assets: [
        "CHANGELOG.md",
        "gradle.properties",
        "tests/end-to-end/build.gradle.kts"
      ],
      message: "chore(release): cut wallet sdk version ${nextRelease.version}

        ${nextRelease.notes}",
    },
  ]
  - [
    "semantic-release-slack-bot",
    {
      notifyOnSuccess: true,
      notifyOnFail: true,
      markdownReleaseNotes: true,
      onSuccessTemplate:
        {text: "A new version of `$package_name` successfully released!\n
            Version: `v$npm_package_version`\n
            Tag: $repo_url/releases/tag/v$npm_package_version\n
            \n
            Release notes:\n
            $release_notes"},
    },
  ]
