package org.hyperledger.identus.walletsdk.edgeagent

const val DIDCOMM1 = "#didcomm-1"
const val PRISM = "prism"
const val JWT_MEDIA_TYPE = "prism/jwt"
const val SDJWT_MEDIA_TYPE = "vc+sd-jwt"
const val PROTOCOL_TYPE = "ProtocolType"
const val GOAL_CODE = "goal_code"
const val WILL_CONFIRM = "will_confirm"
const val PROOF_TYPES = "proof_types"
const val MESSAGE_ID_LIST = "message_id_list"
const val OOB = "_oob"
const val FROM = "from"
const val ROUTING_DID = "routing_did"
const val RECEPIENT_DID = "recipient_did"
const val ADD = "add"
const val UPDATES = "updates"
const val EMPTY_BODY = "{}"
const val ATTACH_ID = "attach_id"
const val REPLACEMENT_ID = "replacement_id"
const val MORE_AVAILABLE = "more_available"
const val MULTIPLE_AVAILABLE = "multiple_available"
const val CREDENTIAL_PREVIEW = "credential_preview"
