object Plugins {
    const val multiplatform = "multiplatform"
    const val serialization = "plugin.serialization"
    const val androidLibrary = "com.android.library"
    const val protobuf = "com.google.protobuf"
    const val npmPublish = "dev.petuska.npm.publish"
    const val gitVersion = "com.palantir.git-version"
    const val klint = "org.jlleitschuh.gradle.ktlint"
    const val multiplatformSwift = "com.chromaticnoise.multiplatform-swiftpackage"
    const val kfcDefinitions = "com.github.turansky.kfc.definitions"
    const val compatibilityValidator = "org.jetbrains.kotlinx.binary-compatibility-validator"
    const val gitOps = "org.ajoberstar.grgit"
    const val koverage = "org.jetbrains.kotlinx.kover"
    const val dokka = "org.jetbrains.dokka"
}